### ISSUE TITLE
Problem Regarding Preparing Data for CA model

### ISSUE THREAD

**Issue by liangxi11** [LittleYUYU/CoaCor#2]
Hi,

In Dataset.py, I find that data mainly have 4 parts (src, tgt, qt, indices). Through preprocess.py, I recognize that src and tgt are indexs of codes and annotations respectively. The indices have 3 parts (qt_idx, qb_idx, code_idx).

However, I can not find the meaning of qt, so I do not know how to prepare this part including qt_index in indices.

I have <NL description, Code Snippet> pairs in c#, and I want  to prepare the data to train the CA model.

Best!

Xiran

**Comment by LittleYUYU** [comment]
Hi Xiran,

Thank you for your interest in our work! 

"qt" is a variable that we used in our preliminary study, which has been removed in our final experiments. We are sorry for not cleaning up all such outdated things. We are working on a cleaner data reprocessing script to get rid of the troubles (parts have been revised, others should be done in a few days). Before that, you may use the preprocessed data we provided (https://github.com/LittleYUYU/CoaCor#processed-data) to run through the pipeline and let us know if there's any problem. We appreciate your feedback;)

**UPDATE**: 
Please take a look at [the new "Source Data" README section](https://github.com/LittleYUYU/CoaCor#source-data). We uploaded a more complete folder of source data and the instructions for data reprocessing. **Please ensure you have pulled down the latest code before running this step.** 

I tested the script, retrained the code generation model with the resulting preprocessed data, and did not observe any bugs. For your application, you may look at the required data here (https://github.com/LittleYUYU/CoaCor/blob/master/code/code_annotation/run.py#L10) and prepare yours similarly. Let me know if this helps.

--Ziyu
